# Generated by Django 3.2 on 2021-04-10 19:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_capsula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/dash/Pictures/py_capsula'), upload_to=''),
        ),
    ]
