# Generated by Django 3.2 on 2021-04-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_capsula', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
